### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AClarkie** [helmfile/vals#34]
I've downloaded the latest release for both `tfstate-lookup` and `val` but running val causes a runtime error when running against state stored in an s3 bucket

```
tfstate-lookup -s .terraform/terraform.tfstate output.access_cert.value
```

Returns the correct value, authentication works fine with the bucket.

```
echo 'foo: ref+tfstate://.terraform/terraform.tfstate/output.access_cert.value' | vals eval -f -
```

Causes a crash:
```
(⎈ |ew1-test-01:default)➜  helm git:(master) ✗ echo 'foo: ref+tfstate://.terraform/terraform.tfstate/output.access_cert.value' | vals eval -f -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1bf8a02]

goroutine 1 [running]:
github.com/fujiwara/tfstate-lookup/tfstate.(*TFState).output(0x0, 0xc000113e9d, 0x18, 0x1db3301, 0xc000627c20, 0x0)
        /home/runner/go/pkg/mod/github.com/fujiwara/tfstate-lookup@v0.0.9/tfstate/lookup.go:152 +0xb2
github.com/fujiwara/tfstate-lookup/tfstate.(*TFState).Lookup(0x0, 0xc000113e9d, 0x18, 0x2473fc0, 0xc0002e64c0, 0xc000113e9d)
        /home/runner/go/pkg/mod/github.com/fujiwara/tfstate-lookup@v0.0.9/tfstate/lookup.go:159 +0x2e4
github.com/variantdev/vals/pkg/providers/tfstate.(*provider).GetString(0x2d6f480, 0xc000113e80, 0x35, 0x0, 0x0, 0xc000113e00, 0x35)
        /home/runner/work/vals/vals/pkg/providers/tfstate/tfstate.go:33 +0x193
github.com/variantdev/vals.(*Runtime).Eval.func3(0xc0000da004, 0x3f, 0x43, 0xc000113e40, 0x8, 0x8)
        /home/runner/work/vals/vals/vals.go:237 +0xe76
github.com/variantdev/vals/pkg/expansion.(*ExpandRegexMatch).InString(0xc000531870, 0xc0000da000, 0x43, 0xc0003c0830, 0x10, 0x1009e13, 0x1de5760)
        /home/runner/work/vals/vals/pkg/expansion/expand_match.go:40 +0xe1
github.com/variantdev/vals/pkg/expansion.(*ExpandRegexMatch).InMap.func1(0xc0000da000, 0x43, 0xc0003c0830, 0xc0000e87e0, 0x8e00000001d27f20, 0xc0003c0860)
        /home/runner/work/vals/vals/pkg/expansion/expand_match.go:52 +0x42
github.com/variantdev/vals/pkg/expansion.ModifyStringValues(0x1d27f20, 0xc0003c0860, 0xc000531808, 0x1d27f20, 0xc0003c0860, 0xc0000c7500, 0x0)
        /home/runner/work/vals/vals/pkg/expansion/maputil.go:42 +0xe63
github.com/variantdev/vals/pkg/expansion.ModifyStringValues(0x1d9f8c0, 0xc0002d2b70, 0xc000531808, 0xc000531818, 0x100c468, 0x30, 0x1e2eb00)
        /home/runner/work/vals/vals/pkg/expansion/maputil.go:83 +0x2f6
github.com/variantdev/vals/pkg/expansion.(*ExpandRegexMatch).InMap(0xc000531870, 0xc0002d2b70, 0x1c50be5, 0x200, 0x0)
        /home/runner/work/vals/vals/pkg/expansion/expand_match.go:51 +0x66
github.com/variantdev/vals.(*Runtime).Eval(0xc0002d2c60, 0xc0002d2b70, 0xc0002d2c60, 0x0, 0x0)
        /home/runner/work/vals/vals/vals.go:286 +0xcd
github.com/variantdev/vals.Eval(0xc0002d2b70, 0xc0005319e8, 0x1, 0x1, 0x0, 0x0, 0xc000489418)
        /home/runner/work/vals/vals/vals.go:377 +0x8c
main.main()
        /home/runner/work/vals/vals/cmd/vals/main.go:76 +0x1430
```

**Comment by andrewnazarov** [comment]
Experiencing the same, but for GCS backend:

```
$ terraform output
external-ip = 111.222.333.444
$ ls -al .terraform/terraform.tfstate
-rw-r--r--    1 root     root           681 Sep  6 15:22 .terraform/terraform.tfstate
$ echo 'foo: ref+tfstate://.terraform/terraform.tfstate/output.external-ip.value' | vals eval -f -
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xffb8f2]
goroutine 1 [running]:
github.com/fujiwara/tfstate-lookup/tfstate.(*TFState).output(0x0, 0xc0002d19dd, 0x18, 0x4e9201, 0x11b8400, 0xc0002f4ae0)
	/go/pkg/mod/github.com/fujiwara/tfstate-lookup@v0.0.9/tfstate/lookup.go:152 +0xb2
github.com/fujiwara/tfstate-lookup/tfstate.(*TFState).Lookup(0x0, 0xc0002d19dd, 0x18, 0x1877460, 0xc0004c2050, 0xc0002d19dd)
	/go/pkg/mod/github.com/fujiwara/tfstate-lookup@v0.0.9/tfstate/lookup.go:159 +0x2e4
github.com/variantdev/vals/pkg/providers/tfstate.(*provider).GetString(0x216d9a8, 0xc0002d19c0, 0x35, 0x0, 0x0, 0xc0002d1900, 0x35)
	/go/src/vals/pkg/providers/tfstate/tfstate.go:33 +0x193
github.com/variantdev/vals.(*Runtime).Eval.func3(0xc000040144, 0x3f, 0x43, 0xc0002d1980, 0x8, 0x8)
	/go/src/vals/vals.go:237 +0xe76
github.com/variantdev/vals/pkg/expansion.(*ExpandRegexMatch).InString(0xc000541870, 0xc000040140, 0x43, 0xc0003bdcc0, 0x10, 0x40bd73, 0x11ea800)
	/go/src/vals/pkg/expansion/expand_match.go:40 +0xe1
github.com/variantdev/vals/pkg/expansion.(*ExpandRegexMatch).InMap.func1(0xc000040140, 0x43, 0xc0003bdcc0, 0xc00023b0e0, 0x470000000112d040, 0xc0003bdcf0)
	/go/src/vals/pkg/expansion/expand_match.go:52 +0x42
github.com/variantdev/vals/pkg/expansion.ModifyStringValues(0x112d040, 0xc0003bdcf0, 0xc000541808, 0x112d040, 0xc0003bdcf0, 0xc0000d9500, 0x0)
	/go/src/vals/pkg/expansion/maputil.go:42 +0xe63
github.com/variantdev/vals/pkg/expansion.ModifyStringValues(0x11a48e0, 0xc0003fa300, 0xc000541808, 0xc000541818, 0x40e2f8, 0x30, 0x1233680)
	/go/src/vals/pkg/expansion/maputil.go:83 +0x2f6
github.com/variantdev/vals/pkg/expansion.(*ExpandRegexMatch).InMap(0xc000541870, 0xc0003fa300, 0x10535d5, 0x200, 0x0)
	/go/src/vals/pkg/expansion/expand_match.go:51 +0x66
github.com/variantdev/vals.(*Runtime).Eval(0xc0003fa3f0, 0xc0003fa300, 0xc0003fa3f0, 0x0, 0x0)
	/go/src/vals/vals.go:286 +0xcd
github.com/variantdev/vals.Eval(0xc0003fa300, 0xc0005419e8, 0x1, 0x1, 0x0, 0x0, 0xc00003f090)
	/go/src/vals/vals.go:377 +0x8c
main.main()
	/go/src/vals/cmd/vals/main.go:76 +0x1430
```

Initially, it didn't work for Helmfile. Then I started playing with the `vals` binary.

vals: v0.10.0
tf: 0.12.29

**Comment by mumoshu** [comment]
@AClarkie @andrewnazarov Thanks for reporting! I managed to reproduce this using S3 backend, but only when the local tfstate file is missing due to e.g. typo.

So I'm still assuming this has something to do with vals inability to access the tfstate file, but only when you used tfstate-lookup from vals. I also found that vals had a bug that resulted in ignoring the file access error, which resulted in tfstate-lookup to panic without any helpful error. I fixed that.

I also updated tfstate-lookup bundled in vals, and will do so for helmfile too.

Would you mind giving it a shot once again with latest vals and helmfile to see if it fix the issue, or at least gives you a better error?

**Comment by mumoshu** [comment]
I believe this was due to an upstream issue and since no one has reported this recently, we're good now!
Thanks for your support everyone.
